.TH PRAKTICALC 1 "2026-05-15" "PraktiCalc 1.5"
.SH NAME
prakticalc \- a practical calculator written in Python with Tkinter and TTK
.SH SYNOPSIS
.B prakticalc
.RI [ options ]
.SH DESCRIPTION
.B prakticalc
is a practical calculator with GUI featuring a calculating history, an extension system & dark mode, as well as integration for many dialog tools.

.SH OPTIONS
.TP
.B --debug
Adds a button into the main window that prints the values of the calculation variables.
.TP
.B --console
Shows the PraktiCalc Console, which is a more advanced tool for debugging. It has a help command that lists all the commands.
.TP
.B --notheming
Disables theming.
.TP
.B --help
Prints a list of all available commands with short descriptions.
.TP
.B --version
Prints the version number.
.SH AUTHOR
Written by Karl Wesseler.
